### ISSUE TITLE
add a feature to logout

### ISSUE THREAD

**Issue by ragsstevens** [ShashankJc1/pathfinderx#25]
As a developer, I want to implement a Logout feature so that users can securely end their session and log out of the travel app.

**Comment by JinalShah31** [comment]
Requirements:

- Logout Button: Add a prominent "Logout" button in the app’s navigation or profile menu.
- Session Termination: Upon clicking the button, the user’s session should be terminated, removing any authentication tokens or session data.
- Redirect: After logout, redirect users to the app's homepage or login screen.
- Confirmation Message: Optionally, display a confirmation message indicating that the logout was successful.

Acceptance Criteria:

-  A "Logout" button is visible and accessible to users.
-  Clicking the button terminates the user session.
-  Users are redirected to the homepage or login screen after logging out.
-  A confirmation message is displayed (if implemented).
