### ISSUE TITLE
add a UI to edit profile

### ISSUE THREAD

**Issue by ragsstevens** [ShashankJc1/pathfinderx#26]
As a developer, I want to implement a Profile Edit UI so that users can update their personal information, such as their name, email, password, and other profile details as the page should have an intuitive design with input fields for editable information.

**Comment by JinalShah31** [comment]
Requirements:

1. Profile Edit Form: Include fields for:

- Name, Email, Phone, Address, Bio, and Password.
- Pre-fill fields with the user's existing data.

2. Input Validation:

- Ensure valid email format and password complexity.
- Prevent duplicate email addresses if applicable.

3. Password Update: Provide separate fields for changing the password, with proper validation.
4. Save and Cancel Buttons:

- "Save" button to update information.
- "Cancel" button to discard changes and return to the profile view.

5. Feedback: Display success or error messages based on the result of the update.

Acceptance Criteria:

-  Users can edit and update their profile information.
-  Fields are pre-filled with existing user data.
-  Input validation is enforced.
-  Users can change their password securely.
-  Save and Cancel buttons function correctly.
-  Success or error messages are displayed as needed.
