### ISSUE TITLE
Add a Calendar in the profile page

### ISSUE THREAD

**Issue by ragsstevens** [ShashankJc1/pathfinderx#36]
As a developer, I want to integrate a calendar feature, so that users can view bookings or reminders within the application.

**Comment by JinalShah31** [comment]
Requirements:

- Calendar Display: Implement a calendar view that shows the current month and allows users to navigate between months.
- Event Management: Users should be able to:
- Add events with details (title, date, time, description).
- Edit or delete existing events.

Acceptance Criteria:

-  Calendar is displayed on the user profile page.
-  Users can add, edit, and delete events.
-  Dates with events are visually indicated.
