### ISSUE TITLE
add a save UI element

### ISSUE THREAD

**Issue by ragsstevens** [ShashankJc1/pathfinderx#41]
As a developer, i would like to add a save option for better user experience to implement a Save feature for destinations, hotels, or itineraries so that users can bookmark and access their favorite items easily.

**Comment by JinalShah31** [comment]
Requirements:

- Save Button: Add a "Save" button to all relevant forms (e.g., profile details, settings).
- Functionality:
- The button should save the current state of the form without submitting it.
- Users should receive a confirmation message indicating that their progress has been saved.

Acceptance Criteria:

-  "Save" button is present on all relevant forms.
-  Clicking "Save" retains the current data without form submission.
-  Users receive a confirmation message upon saving.
